// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3NOf5NM7iqAm4_ZeTdT1SwTRWmkGP5j8',
    appId: '1:895284891256:web:f644759887c401deace78d',
    messagingSenderId: '895284891256',
    projectId: 'fluttersfirecrud',
    authDomain: 'fluttersfirecrud.firebaseapp.com',
    storageBucket: 'fluttersfirecrud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcIKBwZfvn9QR1dMHiHN_OdQmAl3L1QrQ',
    appId: '1:895284891256:android:f265722eaa9d6147ace78d',
    messagingSenderId: '895284891256',
    projectId: 'fluttersfirecrud',
    storageBucket: 'fluttersfirecrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeD47MggIRk9v7qfz5nejs0D3iVqDb0Y',
    appId: '1:895284891256:ios:1bec07bd71dcc968ace78d',
    messagingSenderId: '895284891256',
    projectId: 'fluttersfirecrud',
    storageBucket: 'fluttersfirecrud.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeD47MggIRk9v7qfz5nejs0D3iVqDb0Y',
    appId: '1:895284891256:ios:1bec07bd71dcc968ace78d',
    messagingSenderId: '895284891256',
    projectId: 'fluttersfirecrud',
    storageBucket: 'fluttersfirecrud.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3NOf5NM7iqAm4_ZeTdT1SwTRWmkGP5j8',
    appId: '1:895284891256:web:aa9e0e2ce1c6bbe8ace78d',
    messagingSenderId: '895284891256',
    projectId: 'fluttersfirecrud',
    authDomain: 'fluttersfirecrud.firebaseapp.com',
    storageBucket: 'fluttersfirecrud.appspot.com',
  );

}