// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJ9wko2w6T19c_f_4hknw7i8SF_Nk1i8',
    appId: '1:450921493626:web:ea05ab42ae3b62c861b7c3',
    messagingSenderId: '450921493626',
    projectId: 'notes-5bdbb',
    authDomain: 'notes-5bdbb.firebaseapp.com',
    storageBucket: 'notes-5bdbb.appspot.com',
    measurementId: 'G-E3B2Y7K42L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABYYgkdrAyUdAxQBfHFirn-bs2ofwcjNg',
    appId: '1:450921493626:android:c1b8234c2650418261b7c3',
    messagingSenderId: '450921493626',
    projectId: 'notes-5bdbb',
    storageBucket: 'notes-5bdbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAif8gjvMHLUGfm1GU5FZaSvSXyIZhcKAg',
    appId: '1:450921493626:ios:51cb8fa01f45275c61b7c3',
    messagingSenderId: '450921493626',
    projectId: 'notes-5bdbb',
    storageBucket: 'notes-5bdbb.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAif8gjvMHLUGfm1GU5FZaSvSXyIZhcKAg',
    appId: '1:450921493626:ios:51cb8fa01f45275c61b7c3',
    messagingSenderId: '450921493626',
    projectId: 'notes-5bdbb',
    storageBucket: 'notes-5bdbb.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDJ9wko2w6T19c_f_4hknw7i8SF_Nk1i8',
    appId: '1:450921493626:web:2a9d03ffc4c805ba61b7c3',
    messagingSenderId: '450921493626',
    projectId: 'notes-5bdbb',
    authDomain: 'notes-5bdbb.firebaseapp.com',
    storageBucket: 'notes-5bdbb.appspot.com',
    measurementId: 'G-PR4HHP4PX9',
  );
}
